// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: share/v1/share.proto

package sharepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ShareServiceClient is the client API for ShareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShareServiceClient interface {
	ShareChat(ctx context.Context, in *ShareChatReq, opts ...grpc.CallOption) (*ShareChatRsp, error)
	CheckShareChat(ctx context.Context, in *CheckShareChatReq, opts ...grpc.CallOption) (*CheckShareChatRsp, error)
	UnshareChat(ctx context.Context, in *UnshareChatReq, opts ...grpc.CallOption) (*UnshareChatRsp, error)
	GetChatInfo(ctx context.Context, in *GetChatInfoReq, opts ...grpc.CallOption) (*GetChatInfoRsp, error)
	ShareDoc(ctx context.Context, in *ShareDocReq, opts ...grpc.CallOption) (*ShareDocRsp, error)
	UnshareDoc(ctx context.Context, in *UnshareDocReq, opts ...grpc.CallOption) (*UnshareDocRsp, error)
	GetDocInfo(ctx context.Context, in *GetDocInfoReq, opts ...grpc.CallOption) (*GetDocInfoRsp, error)
	CheckShareDoc(ctx context.Context, in *CheckShareDocReq, opts ...grpc.CallOption) (*CheckShareDocRsp, error)
	GetAudioInfo(ctx context.Context, in *GetAudioInfoReq, opts ...grpc.CallOption) (*GetAudioInfoRsp, error)
	GetAudioChatInfo(ctx context.Context, in *GetAudioChatInfoReq, opts ...grpc.CallOption) (*GetAudioChatInfoRsp, error)
	ShareAudio(ctx context.Context, in *ShareAudioReq, opts ...grpc.CallOption) (*ShareAudioRsp, error)
	UnshareAudio(ctx context.Context, in *UnshareAudioReq, opts ...grpc.CallOption) (*UnshareAudioRsp, error)
	CheckAudio(ctx context.Context, in *CheckAudioReq, opts ...grpc.CallOption) (*CheckAudioRsp, error)
	GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoRsp, error)
	// 获取公司数据
	GetCompanyInfo(ctx context.Context, in *GetCompanyInfoReq, opts ...grpc.CallOption) (*GetCompanyInfoRsp, error)
	// 获取公司行情指标
	GetIndicators(ctx context.Context, in *GetIndicatorsReq, opts ...grpc.CallOption) (*GetIndicatorsRsp, error)
	// 获取公司股权结构
	GetShareholders(ctx context.Context, in *GetShareholdersReq, opts ...grpc.CallOption) (*GetShareholdersRsp, error)
	// 获取公司管理层信息
	GetExecutives(ctx context.Context, in *GetExecutivesReq, opts ...grpc.CallOption) (*GetExecutivesRsp, error)
	// 获取员工构成
	GetStaffInfo(ctx context.Context, in *GetStaffInfoReq, opts ...grpc.CallOption) (*GetStaffInfoRsp, error)
	// 获取主营营收
	GetMBRevenue(ctx context.Context, in *GetMBRevenueReq, opts ...grpc.CallOption) (*GetMBRevenueRsp, error)
	// 获取财务概况
	GetFinancial(ctx context.Context, in *GetFinancialReq, opts ...grpc.CallOption) (*GetFinancialRsp, error)
	// 获取应收款
	GetAccountsReceivable(ctx context.Context, in *GetAccountsReceivableReq, opts ...grpc.CallOption) (*GetAccountsReceivableRsp, error)
	// 获取研发支出
	GetRdExpenditure(ctx context.Context, in *GetRdExpenditureReq, opts ...grpc.CallOption) (*GetRdExpenditureRsp, error)
	ShareVideo(ctx context.Context, in *ShareVideoReq, opts ...grpc.CallOption) (*ShareVideoRsp, error)
	UnshareVideo(ctx context.Context, in *UnshareVideoReq, opts ...grpc.CallOption) (*UnshareVideoRsp, error)
	GetVideoChatInfo(ctx context.Context, in *GetVideoChatInfoReq, opts ...grpc.CallOption) (*GetVideoChatInfoRsp, error)
}

type shareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShareServiceClient(cc grpc.ClientConnInterface) ShareServiceClient {
	return &shareServiceClient{cc}
}

func (c *shareServiceClient) ShareChat(ctx context.Context, in *ShareChatReq, opts ...grpc.CallOption) (*ShareChatRsp, error) {
	out := new(ShareChatRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/ShareChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) CheckShareChat(ctx context.Context, in *CheckShareChatReq, opts ...grpc.CallOption) (*CheckShareChatRsp, error) {
	out := new(CheckShareChatRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/CheckShareChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UnshareChat(ctx context.Context, in *UnshareChatReq, opts ...grpc.CallOption) (*UnshareChatRsp, error) {
	out := new(UnshareChatRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/UnshareChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetChatInfo(ctx context.Context, in *GetChatInfoReq, opts ...grpc.CallOption) (*GetChatInfoRsp, error) {
	out := new(GetChatInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetChatInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ShareDoc(ctx context.Context, in *ShareDocReq, opts ...grpc.CallOption) (*ShareDocRsp, error) {
	out := new(ShareDocRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/ShareDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UnshareDoc(ctx context.Context, in *UnshareDocReq, opts ...grpc.CallOption) (*UnshareDocRsp, error) {
	out := new(UnshareDocRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/UnshareDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetDocInfo(ctx context.Context, in *GetDocInfoReq, opts ...grpc.CallOption) (*GetDocInfoRsp, error) {
	out := new(GetDocInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetDocInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) CheckShareDoc(ctx context.Context, in *CheckShareDocReq, opts ...grpc.CallOption) (*CheckShareDocRsp, error) {
	out := new(CheckShareDocRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/CheckShareDoc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetAudioInfo(ctx context.Context, in *GetAudioInfoReq, opts ...grpc.CallOption) (*GetAudioInfoRsp, error) {
	out := new(GetAudioInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetAudioInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetAudioChatInfo(ctx context.Context, in *GetAudioChatInfoReq, opts ...grpc.CallOption) (*GetAudioChatInfoRsp, error) {
	out := new(GetAudioChatInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetAudioChatInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ShareAudio(ctx context.Context, in *ShareAudioReq, opts ...grpc.CallOption) (*ShareAudioRsp, error) {
	out := new(ShareAudioRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/ShareAudio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UnshareAudio(ctx context.Context, in *UnshareAudioReq, opts ...grpc.CallOption) (*UnshareAudioRsp, error) {
	out := new(UnshareAudioRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/UnshareAudio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) CheckAudio(ctx context.Context, in *CheckAudioReq, opts ...grpc.CallOption) (*CheckAudioRsp, error) {
	out := new(CheckAudioRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/CheckAudio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetVideoInfo(ctx context.Context, in *GetVideoInfoReq, opts ...grpc.CallOption) (*GetVideoInfoRsp, error) {
	out := new(GetVideoInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetVideoInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetCompanyInfo(ctx context.Context, in *GetCompanyInfoReq, opts ...grpc.CallOption) (*GetCompanyInfoRsp, error) {
	out := new(GetCompanyInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetCompanyInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetIndicators(ctx context.Context, in *GetIndicatorsReq, opts ...grpc.CallOption) (*GetIndicatorsRsp, error) {
	out := new(GetIndicatorsRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetIndicators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetShareholders(ctx context.Context, in *GetShareholdersReq, opts ...grpc.CallOption) (*GetShareholdersRsp, error) {
	out := new(GetShareholdersRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetShareholders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetExecutives(ctx context.Context, in *GetExecutivesReq, opts ...grpc.CallOption) (*GetExecutivesRsp, error) {
	out := new(GetExecutivesRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetExecutives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetStaffInfo(ctx context.Context, in *GetStaffInfoReq, opts ...grpc.CallOption) (*GetStaffInfoRsp, error) {
	out := new(GetStaffInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetStaffInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetMBRevenue(ctx context.Context, in *GetMBRevenueReq, opts ...grpc.CallOption) (*GetMBRevenueRsp, error) {
	out := new(GetMBRevenueRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetMBRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetFinancial(ctx context.Context, in *GetFinancialReq, opts ...grpc.CallOption) (*GetFinancialRsp, error) {
	out := new(GetFinancialRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetFinancial", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetAccountsReceivable(ctx context.Context, in *GetAccountsReceivableReq, opts ...grpc.CallOption) (*GetAccountsReceivableRsp, error) {
	out := new(GetAccountsReceivableRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetAccountsReceivable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetRdExpenditure(ctx context.Context, in *GetRdExpenditureReq, opts ...grpc.CallOption) (*GetRdExpenditureRsp, error) {
	out := new(GetRdExpenditureRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetRdExpenditure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) ShareVideo(ctx context.Context, in *ShareVideoReq, opts ...grpc.CallOption) (*ShareVideoRsp, error) {
	out := new(ShareVideoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/ShareVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) UnshareVideo(ctx context.Context, in *UnshareVideoReq, opts ...grpc.CallOption) (*UnshareVideoRsp, error) {
	out := new(UnshareVideoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/UnshareVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shareServiceClient) GetVideoChatInfo(ctx context.Context, in *GetVideoChatInfoReq, opts ...grpc.CallOption) (*GetVideoChatInfoRsp, error) {
	out := new(GetVideoChatInfoRsp)
	err := c.cc.Invoke(ctx, "/chatfinbot.share.v1.ShareService/GetVideoChatInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShareServiceServer is the server API for ShareService service.
// All implementations must embed UnimplementedShareServiceServer
// for forward compatibility
type ShareServiceServer interface {
	ShareChat(context.Context, *ShareChatReq) (*ShareChatRsp, error)
	CheckShareChat(context.Context, *CheckShareChatReq) (*CheckShareChatRsp, error)
	UnshareChat(context.Context, *UnshareChatReq) (*UnshareChatRsp, error)
	GetChatInfo(context.Context, *GetChatInfoReq) (*GetChatInfoRsp, error)
	ShareDoc(context.Context, *ShareDocReq) (*ShareDocRsp, error)
	UnshareDoc(context.Context, *UnshareDocReq) (*UnshareDocRsp, error)
	GetDocInfo(context.Context, *GetDocInfoReq) (*GetDocInfoRsp, error)
	CheckShareDoc(context.Context, *CheckShareDocReq) (*CheckShareDocRsp, error)
	GetAudioInfo(context.Context, *GetAudioInfoReq) (*GetAudioInfoRsp, error)
	GetAudioChatInfo(context.Context, *GetAudioChatInfoReq) (*GetAudioChatInfoRsp, error)
	ShareAudio(context.Context, *ShareAudioReq) (*ShareAudioRsp, error)
	UnshareAudio(context.Context, *UnshareAudioReq) (*UnshareAudioRsp, error)
	CheckAudio(context.Context, *CheckAudioReq) (*CheckAudioRsp, error)
	GetVideoInfo(context.Context, *GetVideoInfoReq) (*GetVideoInfoRsp, error)
	// 获取公司数据
	GetCompanyInfo(context.Context, *GetCompanyInfoReq) (*GetCompanyInfoRsp, error)
	// 获取公司行情指标
	GetIndicators(context.Context, *GetIndicatorsReq) (*GetIndicatorsRsp, error)
	// 获取公司股权结构
	GetShareholders(context.Context, *GetShareholdersReq) (*GetShareholdersRsp, error)
	// 获取公司管理层信息
	GetExecutives(context.Context, *GetExecutivesReq) (*GetExecutivesRsp, error)
	// 获取员工构成
	GetStaffInfo(context.Context, *GetStaffInfoReq) (*GetStaffInfoRsp, error)
	// 获取主营营收
	GetMBRevenue(context.Context, *GetMBRevenueReq) (*GetMBRevenueRsp, error)
	// 获取财务概况
	GetFinancial(context.Context, *GetFinancialReq) (*GetFinancialRsp, error)
	// 获取应收款
	GetAccountsReceivable(context.Context, *GetAccountsReceivableReq) (*GetAccountsReceivableRsp, error)
	// 获取研发支出
	GetRdExpenditure(context.Context, *GetRdExpenditureReq) (*GetRdExpenditureRsp, error)
	ShareVideo(context.Context, *ShareVideoReq) (*ShareVideoRsp, error)
	UnshareVideo(context.Context, *UnshareVideoReq) (*UnshareVideoRsp, error)
	GetVideoChatInfo(context.Context, *GetVideoChatInfoReq) (*GetVideoChatInfoRsp, error)
	mustEmbedUnimplementedShareServiceServer()
}

// UnimplementedShareServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShareServiceServer struct {
}

func (UnimplementedShareServiceServer) ShareChat(context.Context, *ShareChatReq) (*ShareChatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareChat not implemented")
}
func (UnimplementedShareServiceServer) CheckShareChat(context.Context, *CheckShareChatReq) (*CheckShareChatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckShareChat not implemented")
}
func (UnimplementedShareServiceServer) UnshareChat(context.Context, *UnshareChatReq) (*UnshareChatRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnshareChat not implemented")
}
func (UnimplementedShareServiceServer) GetChatInfo(context.Context, *GetChatInfoReq) (*GetChatInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatInfo not implemented")
}
func (UnimplementedShareServiceServer) ShareDoc(context.Context, *ShareDocReq) (*ShareDocRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareDoc not implemented")
}
func (UnimplementedShareServiceServer) UnshareDoc(context.Context, *UnshareDocReq) (*UnshareDocRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnshareDoc not implemented")
}
func (UnimplementedShareServiceServer) GetDocInfo(context.Context, *GetDocInfoReq) (*GetDocInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocInfo not implemented")
}
func (UnimplementedShareServiceServer) CheckShareDoc(context.Context, *CheckShareDocReq) (*CheckShareDocRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckShareDoc not implemented")
}
func (UnimplementedShareServiceServer) GetAudioInfo(context.Context, *GetAudioInfoReq) (*GetAudioInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioInfo not implemented")
}
func (UnimplementedShareServiceServer) GetAudioChatInfo(context.Context, *GetAudioChatInfoReq) (*GetAudioChatInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioChatInfo not implemented")
}
func (UnimplementedShareServiceServer) ShareAudio(context.Context, *ShareAudioReq) (*ShareAudioRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareAudio not implemented")
}
func (UnimplementedShareServiceServer) UnshareAudio(context.Context, *UnshareAudioReq) (*UnshareAudioRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnshareAudio not implemented")
}
func (UnimplementedShareServiceServer) CheckAudio(context.Context, *CheckAudioReq) (*CheckAudioRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAudio not implemented")
}
func (UnimplementedShareServiceServer) GetVideoInfo(context.Context, *GetVideoInfoReq) (*GetVideoInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoInfo not implemented")
}
func (UnimplementedShareServiceServer) GetCompanyInfo(context.Context, *GetCompanyInfoReq) (*GetCompanyInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompanyInfo not implemented")
}
func (UnimplementedShareServiceServer) GetIndicators(context.Context, *GetIndicatorsReq) (*GetIndicatorsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIndicators not implemented")
}
func (UnimplementedShareServiceServer) GetShareholders(context.Context, *GetShareholdersReq) (*GetShareholdersRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShareholders not implemented")
}
func (UnimplementedShareServiceServer) GetExecutives(context.Context, *GetExecutivesReq) (*GetExecutivesRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutives not implemented")
}
func (UnimplementedShareServiceServer) GetStaffInfo(context.Context, *GetStaffInfoReq) (*GetStaffInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStaffInfo not implemented")
}
func (UnimplementedShareServiceServer) GetMBRevenue(context.Context, *GetMBRevenueReq) (*GetMBRevenueRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMBRevenue not implemented")
}
func (UnimplementedShareServiceServer) GetFinancial(context.Context, *GetFinancialReq) (*GetFinancialRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinancial not implemented")
}
func (UnimplementedShareServiceServer) GetAccountsReceivable(context.Context, *GetAccountsReceivableReq) (*GetAccountsReceivableRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountsReceivable not implemented")
}
func (UnimplementedShareServiceServer) GetRdExpenditure(context.Context, *GetRdExpenditureReq) (*GetRdExpenditureRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRdExpenditure not implemented")
}
func (UnimplementedShareServiceServer) ShareVideo(context.Context, *ShareVideoReq) (*ShareVideoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareVideo not implemented")
}
func (UnimplementedShareServiceServer) UnshareVideo(context.Context, *UnshareVideoReq) (*UnshareVideoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnshareVideo not implemented")
}
func (UnimplementedShareServiceServer) GetVideoChatInfo(context.Context, *GetVideoChatInfoReq) (*GetVideoChatInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoChatInfo not implemented")
}
func (UnimplementedShareServiceServer) mustEmbedUnimplementedShareServiceServer() {}

// UnsafeShareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShareServiceServer will
// result in compilation errors.
type UnsafeShareServiceServer interface {
	mustEmbedUnimplementedShareServiceServer()
}

func RegisterShareServiceServer(s grpc.ServiceRegistrar, srv ShareServiceServer) {
	s.RegisterService(&ShareService_ServiceDesc, srv)
}

func _ShareService_ShareChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ShareChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/ShareChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ShareChat(ctx, req.(*ShareChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_CheckShareChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckShareChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CheckShareChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/CheckShareChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CheckShareChat(ctx, req.(*CheckShareChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UnshareChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UnshareChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/UnshareChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UnshareChat(ctx, req.(*UnshareChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetChatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetChatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetChatInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetChatInfo(ctx, req.(*GetChatInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ShareDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareDocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ShareDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/ShareDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ShareDoc(ctx, req.(*ShareDocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UnshareDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareDocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UnshareDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/UnshareDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UnshareDoc(ctx, req.(*UnshareDocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetDocInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetDocInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetDocInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetDocInfo(ctx, req.(*GetDocInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_CheckShareDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckShareDocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CheckShareDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/CheckShareDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CheckShareDoc(ctx, req.(*CheckShareDocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetAudioInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetAudioInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetAudioInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetAudioInfo(ctx, req.(*GetAudioInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetAudioChatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudioChatInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetAudioChatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetAudioChatInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetAudioChatInfo(ctx, req.(*GetAudioChatInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ShareAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ShareAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/ShareAudio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ShareAudio(ctx, req.(*ShareAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UnshareAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UnshareAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/UnshareAudio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UnshareAudio(ctx, req.(*UnshareAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_CheckAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).CheckAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/CheckAudio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).CheckAudio(ctx, req.(*CheckAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetVideoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetVideoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetVideoInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetVideoInfo(ctx, req.(*GetVideoInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetCompanyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetCompanyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetCompanyInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetCompanyInfo(ctx, req.(*GetCompanyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetIndicators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndicatorsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetIndicators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetIndicators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetIndicators(ctx, req.(*GetIndicatorsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetShareholders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareholdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetShareholders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetShareholders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetShareholders(ctx, req.(*GetShareholdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetExecutives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutivesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetExecutives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetExecutives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetExecutives(ctx, req.(*GetExecutivesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetStaffInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStaffInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetStaffInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetStaffInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetStaffInfo(ctx, req.(*GetStaffInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetMBRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMBRevenueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetMBRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetMBRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetMBRevenue(ctx, req.(*GetMBRevenueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetFinancial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinancialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetFinancial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetFinancial",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetFinancial(ctx, req.(*GetFinancialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetAccountsReceivable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsReceivableReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetAccountsReceivable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetAccountsReceivable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetAccountsReceivable(ctx, req.(*GetAccountsReceivableReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetRdExpenditure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRdExpenditureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetRdExpenditure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetRdExpenditure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetRdExpenditure(ctx, req.(*GetRdExpenditureReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_ShareVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).ShareVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/ShareVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).ShareVideo(ctx, req.(*ShareVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_UnshareVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnshareVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).UnshareVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/UnshareVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).UnshareVideo(ctx, req.(*UnshareVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShareService_GetVideoChatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoChatInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShareServiceServer).GetVideoChatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatfinbot.share.v1.ShareService/GetVideoChatInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShareServiceServer).GetVideoChatInfo(ctx, req.(*GetVideoChatInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ShareService_ServiceDesc is the grpc.ServiceDesc for ShareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatfinbot.share.v1.ShareService",
	HandlerType: (*ShareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareChat",
			Handler:    _ShareService_ShareChat_Handler,
		},
		{
			MethodName: "CheckShareChat",
			Handler:    _ShareService_CheckShareChat_Handler,
		},
		{
			MethodName: "UnshareChat",
			Handler:    _ShareService_UnshareChat_Handler,
		},
		{
			MethodName: "GetChatInfo",
			Handler:    _ShareService_GetChatInfo_Handler,
		},
		{
			MethodName: "ShareDoc",
			Handler:    _ShareService_ShareDoc_Handler,
		},
		{
			MethodName: "UnshareDoc",
			Handler:    _ShareService_UnshareDoc_Handler,
		},
		{
			MethodName: "GetDocInfo",
			Handler:    _ShareService_GetDocInfo_Handler,
		},
		{
			MethodName: "CheckShareDoc",
			Handler:    _ShareService_CheckShareDoc_Handler,
		},
		{
			MethodName: "GetAudioInfo",
			Handler:    _ShareService_GetAudioInfo_Handler,
		},
		{
			MethodName: "GetAudioChatInfo",
			Handler:    _ShareService_GetAudioChatInfo_Handler,
		},
		{
			MethodName: "ShareAudio",
			Handler:    _ShareService_ShareAudio_Handler,
		},
		{
			MethodName: "UnshareAudio",
			Handler:    _ShareService_UnshareAudio_Handler,
		},
		{
			MethodName: "CheckAudio",
			Handler:    _ShareService_CheckAudio_Handler,
		},
		{
			MethodName: "GetVideoInfo",
			Handler:    _ShareService_GetVideoInfo_Handler,
		},
		{
			MethodName: "GetCompanyInfo",
			Handler:    _ShareService_GetCompanyInfo_Handler,
		},
		{
			MethodName: "GetIndicators",
			Handler:    _ShareService_GetIndicators_Handler,
		},
		{
			MethodName: "GetShareholders",
			Handler:    _ShareService_GetShareholders_Handler,
		},
		{
			MethodName: "GetExecutives",
			Handler:    _ShareService_GetExecutives_Handler,
		},
		{
			MethodName: "GetStaffInfo",
			Handler:    _ShareService_GetStaffInfo_Handler,
		},
		{
			MethodName: "GetMBRevenue",
			Handler:    _ShareService_GetMBRevenue_Handler,
		},
		{
			MethodName: "GetFinancial",
			Handler:    _ShareService_GetFinancial_Handler,
		},
		{
			MethodName: "GetAccountsReceivable",
			Handler:    _ShareService_GetAccountsReceivable_Handler,
		},
		{
			MethodName: "GetRdExpenditure",
			Handler:    _ShareService_GetRdExpenditure_Handler,
		},
		{
			MethodName: "ShareVideo",
			Handler:    _ShareService_ShareVideo_Handler,
		},
		{
			MethodName: "UnshareVideo",
			Handler:    _ShareService_UnshareVideo_Handler,
		},
		{
			MethodName: "GetVideoChatInfo",
			Handler:    _ShareService_GetVideoChatInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "share/v1/share.proto",
}
